#' wrapper function to add all components to who map
#' code by IZAWA, Yurie & LAURENSON-SCHAFER Henry
#' @details wrapper function to add all components to who map
#' @param sf - list of shapefiles to be used
#' @param xlim - the coordinate limits of the x axis
#' @param ylim - the coordinate limits of the y axis
#' @param box_lims - coodrinate limits supplied as a bounding box generated by sf::st_bbox()
#' @param region - user defined region for logo and disclaimer text
#' @param data_source - user defined data source
#' @param production_team - for the caption, define the team that produced the map.
#'  Defaults to _WHO Health Emergencies Programme_
#' @param include_adm0_line - should the specialised adm0 borders be used?
#' Note that these are borders **excluding** coastlines.
#' @param na_scale - should a new scale for not applicable be added?
#' @param add_no_data_scale - should a new scale for no data be added?
#' @export

who_map_pipeline <- function(sf = whomapper::pull_sfs(adm_level = 0, query_server = FALSE),
                             xlim = NULL,
                             ylim = NULL,
                             box_lims = NULL,
                             box_padding = 0.05,
                             region = "HQ",
                             data_source = "World Health Organization",
                             production_team = "WHO Health Emergencies Programme",
                             include_adm0_line = TRUE,
                             na_scale = TRUE,
                             no_data_scale = TRUE,
                             logo_location = c("topright", "bottomright", "topleft", "bottomleft"),
                             logo_outside_panel = TRUE) {

  ## for some reason emro doesn't have a logo on the brand portal???
  region <- match.arg(str_to_upper(region), c("HQ", "SEARO", "EURO", "WPRO", "AMRO", "PAHO", "AFRO"))


  if (purrr::is_list(sf) & "disp_area" %in% names(sf) & "disp_border" %in% names(sf)) {
    disp_layer <- who_map_disp(sf, na_scale = na_scale, no_data_scale = no_data_scale)
  } else {
    disp_layer <- NULL
    include_adm0_line <- FALSE
  }

  out <- append(
    disp_layer,
    list(who_map_theme(xlim = xlim, ylim = ylim, box_lims = box_lims))
  )

  if (include_adm0_line) {
    out <-
      append(
        out,
        list(geom_sf_who_line(data = sf$adm0_line, linewidth = 0.1))
      )
     # geom_sf(data = sf$adm0_line)
  }

  out <- append(
    out,
    who_map_annotate(region = region,
                     data_source = data_source,
                     production_team = production_team,
                     logo_location = logo_location,
                     logo_outside_panel = logo_outside_panel)
  )


  return(out)

}


