#' theme for WHO maps
#' code by IZAWA, Yurie & LAURENSON-SCHAFER Henry
#' @details theme for WHO maps
#' @param xlim - the coordinate limits of the x axis
#' @param ylim - the coordinate limits of the y axis
#' @param box_lims - coodrinate limits supplied as a bounding box generated by sf::st_bbox()

#' @export


who_map_theme <- function(xlim = NULL, ylim = NULL, box_lims = NULL, box_padding = 0.05) {


  if (is.null(xlim) & is.null(ylim) & !is.null(box_lims)) {
    box_lims <- pad_box(box_lims, box_padding)
    xlim <- c(box_lims[["xmin"]], box_lims[["xmax"]])
    ylim <- c(box_lims[["ymin"]], box_lims[["ymax"]])

  }
  x_exp <- if (!is.null(xlim)) NULL else c(0, 0)
  y_exp <- if (!is.null(ylim)) NULL else c(-80, 100)



  list(
    coord_sf(expand = FALSE, clip = "on", xlim = xlim, ylim = ylim),
    expand_limits(x = x_exp, y = y_exp),
    guides(fill = guide_legend(override.aes = list(col = "black"))),
    theme(
      # Background
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill ="#E6E7E8"),
      axis.text.x = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),

      # Margin around the map
      # plot.margin = unit(c(3,0,5,0), "lines"),

      # Title
      plot.title = element_text(color = who_map_col("title"), size = 16,
                                face = "bold", hjust = 0),
      plot.subtitle = element_text(color = who_map_col("title"), size = 13, hjust = 0),
      plot.caption = element_text(hjust = 0, size = 6),

      # Legend
      legend.position = "right",
      legend.title = element_text(size = 10, face = "bold"),
      legend.text = element_text(size = 10),
      legend.box = "vertical",
      legend.background = element_rect(fill = NA),
      legend.key.size = unit(0.5, 'cm')
    )
  )
}

pad_box <- function(box_lims, mult = 0.05) {

  diff_x <- (box_lims[["xmax"]] - box_lims[["xmin"]]) * mult
  diff_y <- (box_lims[["ymax"]] - box_lims[["ymin"]]) * mult

  box_lims[["xmin"]] <- box_lims[["xmin"]] - diff_x
  box_lims[["xmax"]] <- box_lims[["xmax"]] + diff_x
  box_lims[["ymin"]] <- box_lims[["ymin"]] - diff_y
  box_lims[["ymax"]] <- box_lims[["ymax"]] + diff_y

  box_lims
}

